spring:
  application:
    name: animealth-backend
---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    include: oauth
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Animealth
    username: root
    password: tmdtjq3940
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true